### ISSUE TITLE
[Feature Request]: Support preset dictionary.

### ISSUE THREAD

**Issue by prgm767** [tukaani-project/xz-java#5]
### Describe the Feature

The scaffolding is already there, but it looks like it it not implemented. 
```
Exception in thread "main" java.lang.IllegalArgumentException: XZ doesn't support a preset dictionary for now
```

Could it be?

### Will I try to implement this new feature?

No

**Comment by Larhzu** [comment]
Sorry for the unreasonable delay.

Preset dictionary works with raw LZMA and LZMA2 streams. It's not supported in .xz or .lzma files. There are no plans to add support for it into the .xz format for now.

The implementation with raw streams is a bit weak because initializing the encoder with a big preset dictionary is expensive but there is no API to reuse the initialized state to make it faster to compress multiple files with the same settings. This is true in both XZ for Java and XZ Utils.
